// 400 error : Bad Request
// 서버가 클라이언트 오류(예: 잘못된 요청 구문, 유효하지 않은 요청 메시지 프레이밍, 또는 변조된 요청 라우팅)를
// 감지해 요청을 처리할 수 없거나, 하지 않는다는 것을 의미

export const NO_MATCH_PASSWORD = "NO_MATCH_PASSWORD";
export const NO_MATCH_NICKNAME = "NO_MATCH_NICKNAME";
export const NO_MATCH_USER_ID = "NO_MATCH_USER_ID";
export const NOT_MATCH_REFRESH_TOKEN = "NOT_MATCH_REFRESH_TOKEN";
export const BAD_REQUEST = "BAD_REQUEST";
export const NOT_EXIST_ID = "NOT_EXIST_ID";
export const NOT_EXIST_LIST = "NOT_EXIST_LIST";
export const CONFIRM_REQUIRED_USER_INFORMATION =
  "CONFIRM_REQUIRED_USER_INFORMATION";
export const CONFIRM_REQUIRED_UNIQUE_ID_INFORMATION =
  "CONFIRM_REQUIRED_UNIQUE_ID_INFORMATION";
export const CONFIRM_REQUIRED_NAME_INFORMATION =
  "CONFIRM_REQUIRED_NAME_INFORMATION";
export const CONFIRM_REQUIRED_NICKNAME_INFORMATION =
  "CONFIRM_REQUIRED_NICKNAME_INFORMATION";
export const CONFIRM_REQUIRED_PASSWORD_INFORMATION =
  "CONFIRM_REQUIRED_PASSWORD_INFORMATION";
export const CONFIRM_REQUIRED_PHONE_INFORMATION =
  "CONFIRM_REQUIRED_PHONE_INFORMATION";
export const CONFIRM_REQUIRED_USER_ID_INFORMATION =
  "CONFIRM_REQUIRED_USER_ID_INFORMATION";
export const CONFIRM_REQUIRED_ADDRESS_INFORMATION =
  "CONFIRM_REQUIRED_ADDRESS_INFORMATION";
export const CONFIRM_REQUIRED_CREDITOR_INFORMATION =
  "CONFIRM_REQUIRED_CREDITOR_INFORMATION";
export const CONFIRM_REQUIRED_DEBTOR_INFORMATION =
  "CONFIRM_REQUIRED_DEBTOR_INFORMATION";
export const CONFIRM_REQUIRED_LOAN_INFORMATION =
  "CONFIRM_REQUIRED_LOAN_INFORMATION";
export const CONFIRM_REQUIRED_LOAN_REPAYMENT_DATE_INFORMATION =
  "CONFIRM_REQUIRED_LOAN_REPAYMENT_DATE_INFORMATION";
export const CONFIRM_REQUIRED_LOAN_INTEREST_INFORMATION =
  "CONFIRM_REQUIRED_LOAN_INTEREST_INFORMATION";
