// 400 error : Bad Request
// 서버가 클라이언트 오류(예: 잘못된 요청 구문, 유효하지 않은 요청 메시지 프레이밍, 또는 변조된 요청 라우팅)를
// 감지해 요청을 처리할 수 없거나, 하지 않는다는 것을 의미

// creditors
export const CREDITOR_UNIQUE_ID_REQUIRED = "CREDITOR_UNIQUE_ID_REQUIRED";
export const CREDITORS_CONFIRMATION_ID = "CREDITORS_CONFIRMATION_ID";

// users
export const NO_MATCH_PASSWORD = "NO_MATCH_PASSWORD";
export const NO_MATCH_NICKNAME = "NO_MATCH_NICKNAME";
export const NO_MATCH_USER_ID = "NO_MATCH_USER_ID";
export const NO_MATCH_LOAN_ID = "NO_MATCH_LOAN_ID";
export const NO_MATCH_CREDITOR_UNIQUE_ID = "NO_MATCH_CREDITOR_UNIQUE_ID";
export const NO_MATCH_DEBTOR_UNIQUE_ID = "NO_MATCH_DEBTOR_UNIQUE_ID";
export const NOT_MATCH_REFRESH_TOKEN = "NOT_MATCH_REFRESH_TOKEN";
export const BAD_REQUEST = "BAD_REQUEST";
export const NOT_EXIST_ID = "NOT_EXIST_ID";
export const USER_REQUIRED = "USER_REQUIRED";
export const UNIQUE_ID_REQUIRED = "UNIQUE_ID_REQUIRED";
export const NAME_REQUIRED = "NAME_REQUIRED";
export const NICKNAME_REQUIRED = "NICKNAME_REQUIRED";
export const PASSWORD_REQUIRED = "PASSWORD_REQUIRED";
export const PHONE_REQUIRED = "PHONE_REQUIRED";
export const USER_ID_REQUIRED = "USER_ID_REQUIRED";
export const ADDRESS_REQUIRED = "ADDRESS_REQUIRED";

// loans
// export const CREDITOR_ID_REQUIRED = "CREDITOR_ID_REQUIRED";
export const CREDITOR_UNIQUE_ID_REQUIRED = "CREDITOR_UNIQUE_ID_REQUIRED";
export const DEBTOR_ID_REQUIRED = "DEBTOR_ID_REQUIRED";
export const DEBTOR_UNIQUE_ID_REQUIRED = "DEBTOR_UNIQUE_ID_REQUIRED";
export const LOAN_REQUIRED = "LOAN_REQUIRED";
export const LOAN_REPAYMENT_DATE_REQUIRED = "LOAN_REPAYMENT_DATE_REQUIRED";
export const LOAN_INTEREST_REQUIRED = "LOAN_INTEREST";
export const LOAN_TOTAL_AMOUNT_REQUIRED = "LOAN_TOTAL_AMOUNT_REQUIRED";
export const LOAN_UNIQUE_ID_REQUIRED = "LOAN_UNIQUE_ID_REQUIRED";
export const LOAN_CREDITOR_UNIQUE_ID_REQUIRED =
  "LOAN_CREDITOR_UNIQUE_ID_REQUIRED";
export const LOAN_DEBTOR_UNIQUE_ID_REQUIRED = "LOAN_DEBTOR_UNIQUE_ID_REQUIRED";
